sudo: required
services:
  - docker

before_install:
  - docker build -t smagin07/docker-react -f Dockerfile.dev .

script:
  - docker run smagin07/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "freedronepics"
  env: "docker-react"
  bucket_name: "elasticbeanstalk-us-west-2-002216530280"
  bucket_path: "freedronepics"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secrete_access_key:
    secure: "$AWS_SECRET_KEY"
